name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Corrector
      id: corrector
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: pip install pytest numpy && wget https://www.dlsi.ua.es/~cperez/idspia-correctores/corrector.sh
          && chmod +x corrector.sh && ./corrector.sh
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CORRECTOR_RESULTS: "${{steps.corrector.outputs.result}}"
      with:
        runners: corrector
